---
  APP_DOCS: 'docs'
  SECRET_KEY: 'f593300815283452ffe458531bd57266c39f1'
  SQLALCHEMY_DATABASE_URI: 'sqlite:///database/crowdsorting.db'
  SQLALCHEMY_TRACK_MODIFICATIONS: False
  MAX_CONTENT_LENGTH: 16777216
  CAS_SERVER: "https://cas.byu.edu"
  CAS_AFTER_LOGIN: 'cas_login'
  SESSION_TYPE: 'filesystem'
  FLASK_ADMIN_SWATCH: 'cerulean'
  SELECTION_ALGORITHM: pairall()
  PAIRS_BEING_PROCESSED_PATH: 'crowdsorting/app_resources/pairs_being_processed/pairsBeingProcessed.pkl'
  SUBDIRECTORY_ROOT: 'crowd-sorting'